name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify your Node version here

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  merge:
    needs: test
    if: success()
    runs-on: ubuntu-latest

    steps:
    - name: Auto-merge on successful tests
      uses: actions/github-script@v4
      with:
        script: |
          github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            merge_method: 'merge'
          })
